In [21]:
import cv2
import cv2.aruco as aruco
import numpy as np
import os


def findArucoMarkers(img, markerSize=6, totalMarkers=250, draw=True):
    imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    key = getattr(aruco, f"DICT_{markerSize}X{markerSize}_{totalMarkers}")
    arucoDict = aruco.getPredefinedDictionary(key)
    arucoParam =  aruco.DetectorParameters()
    bboxs, ids, rejected = aruco.detectMarkers(imgGray, arucoDict, parameters=arucoParam)

    print(ids)
    

    
def main():
    cap = cv2.VideoCapture(0)

    while True:
        success, img = cap.read()
        findArucoMarkers(img)
        
        cv2.imshow("Image", cv2.resize(img, (960, 540)))
        k = cv2.waitKey(1)
        
        if k%256 == 27:
            break
        
    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()

[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[123]
 [ 12]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [123]]
[[ 12]
 [1